# Generated by Django 4.0.5 on 2022-06-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_value', models.FloatField(blank=True, max_length=255, null=True)),
                ('MRP_value', models.FloatField(blank=True, max_length=255, null=True)),
                ('tenure', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=255, null=True)),
                ('rental', models.FloatField(blank=True, null=True)),
                ('refundable_security_deposit', models.FloatField(blank=True, default=0, null=True)),
                ('insurance', models.FloatField(blank=True, default=0, null=True)),
                ('monthly_rental', models.FloatField(blank=True, null=True)),
                ('total_amount_payable', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
